---
title: "Learning R 2025"
author: "Ziping Zhang"
format: html
editor: visual
---

```{r set up}
library(tidyverse)
```

# **Data management and wrangling**

```{r import data}
download.file(
  url = "https://zenodo.org/records/4989220/files/Eliasson_data2.csv?download=1",
  destfile = here::here("data/post-meal-insulin.csv")
)
post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))

```

```{r select variables}
# single variables
select(post_meal_data, Age)
# multiple variables
select(post_meal_data, Age, BMI, Weight)
# remove variable
select(post_meal_data, -Group)
# select variables start/end with xxx
select(post_meal_data, starts_with("PG"))
select(post_meal_data, ends_with("DXA"))
# select variables contains xxx 
select(post_meal_data, contains("0"))
```

```{r new datasets}
small_post_meal_data <- select(post_meal_data, id, Age, BMI, Group, auc_pg, auc_ins, glykemi)
small_post_meal_data

```

```{r renaming variables}
small_post_meal_data |>
  rename(auc_glucose = auc_pg)

small_post_meal_data |>
  rename(
    auc_glucose = auc_pg,
    auc_insulin = auc_ins
  )

```

```{r 11.6 exercise}

```

```{r filtering by rows}
small_post_meal_data |>
  filter(glykemi == 1)

small_post_meal_data |>
  filter(BMI >= 25)

small_post_meal_data |>
  filter(Group == "CTR")

```

```{r logical conditions}

TRUE & TRUE
TRUE & FALSE
FALSE & FALSE

TRUE | TRUE
TRUE | FALSE
FALSE | FALSE

TRUE & NA
FALSE & NA
TRUE | NA
FALSE | NA
```

```{r more comlicated filtering}
small_post_meal_data |>
  filter(Group == "CTR", BMI >= 25)

tidier_post_meal_data <- small_post_meal_data |>
  rename(
    auc_glucose = auc_pg,
    auc_insulin = auc_ins
  ) |>
  filter(glykemi == 0) |>
  select(-glykemi)
tidier_post_meal_data

```

```{r add new columns}
tidier_post_meal_data |>
  mutate(insulin_glucose_ratio = auc_insulin / auc_glucose)

tidier_post_meal_data |>
  mutate(
    insulin_glucose_ratio = auc_insulin / auc_glucose,
    Group = if_else(Group == "CTR", "Control", "First-degree relative")
  )


tidied_post_meal_data <- tidier_post_meal_data |>
  mutate(
    insulin_glucose_ratio = auc_insulin / auc_glucose,
    Group = if_else(Group == "CTR", "Control", "First-degree relative")
  )

```

```{r 11.9 excerise}

```

# **Wrangling with visualizing**

```{r Visualizing with a jitter plot}
tidied_post_meal_data |>
  mutate(overweight = if_else(BMI >= 25, "Overweight", "Not overweight")) |>
  ggplot(aes(x = overweight, y = insulin_glucose_ratio)) +
  geom_jitter()
```

##  

```{r Plotting three or more variables}
tidied_post_meal_data |>
  filter(BMI < 30) |>
  ggplot(aes(x = Age, y = auc_insulin, colour = Group)) +
  geom_point()

tidied_post_meal_data |>
  filter(BMI < 30) |>
  mutate(young = if_else(Age < 40, "Young", "Old")) |>
  ggplot(aes(x = BMI, y = insulin_glucose_ratio, colour = Group)) +
  geom_point() +
  facet_grid(cols = vars(young))

tidied_post_meal_data |>
  filter(BMI < 30) |>
  mutate(young = if_else(Age < 40, "Young", "Old")) |>
  ggplot(aes(x = BMI, y = insulin_glucose_ratio, colour = Group)) +
  geom_point() +
  facet_grid(rows = vars(young))
```

```{r 12.4 excercise}

```

```{r 12.6 excercise}

```

## **Titles, axis labels, and themes**

```{r}
base_scatterplot <- tidied_post_meal_data |>
  ggplot(aes(x = BMI, y = insulin_glucose_ratio, colour = Age)) +
  geom_point() +
  facet_grid(cols = vars(Group)) +
  scale_color_viridis_c()
base_scatterplot

base_scatterplot + theme_bw()
base_scatterplot + theme_minimal()
base_scatterplot + theme_classic()

base_scatterplot +
  labs(
    title = "BMI, insulin-to-glucose ratio, and age by group",
    y = "Insulin-to-glucose Ratio",
    x = "BMI (kg/m2)"
  )
```
